"""add customer email and address

Revision ID: d18ac3a542ae
Revises: 06c22506e5bd
Create Date: 2026-08-06 00:10:36.729187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18ac3a542ae'
down_revision: Union[str, Sequence[str], None] = '06c22506e5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('address', sa.String(length=500), nullable=True))
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'customers', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
